"""empty message

Revision ID: 8286fdcdebf4
Revises: df530e0ea561
Create Date: 2022-01-17 13:42:31.838744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8286fdcdebf4'
down_revision = 'df530e0ea561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('grade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'grade')
    # ### end Alembic commands ###
